// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto.proto

package importdedup

import (
	fmt "fmt"
	_ "github.com/waynz0r/protobuf/gogoproto"
	proto "github.com/waynz0r/protobuf/proto"
	github_com_waynz0r_protobuf_test_importdedup_subpkg "github.com/waynz0r/protobuf/test/importdedup/subpkg"
	subpkg "github.com/waynz0r/protobuf/test/importdedup/subpkg"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Object struct {
	CustomField          *github_com_waynz0r_protobuf_test_importdedup_subpkg.CustomType `protobuf:"bytes,1,opt,name=CustomField,customtype=github.com/waynz0r/protobuf/test/importdedup/subpkg.CustomType" json:"CustomField,omitempty"`
	SubObject            *subpkg.SubObject                                               `protobuf:"bytes,2,opt,name=SubObject" json:"SubObject,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                        `json:"-"`
	XXX_unrecognized     []byte                                                          `json:"-"`
	XXX_sizecache        int32                                                           `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}
func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetSubObject() *subpkg.SubObject {
	if m != nil {
		return m.SubObject
	}
	return nil
}

func init() {
	proto.RegisterType((*Object)(nil), "importdedup.Object")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x03, 0x93, 0x42, 0xdc, 0x99, 0xb9, 0x05, 0xf9, 0x45, 0x25, 0x29, 0xa9, 0x29, 0xa5,
	0x05, 0x52, 0x06, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xe5, 0x89,
	0x95, 0x79, 0x55, 0x06, 0x45, 0xfa, 0x60, 0x65, 0x49, 0xa5, 0x69, 0xfa, 0xe9, 0xf9, 0xe9, 0xf9,
	0x60, 0x0e, 0x98, 0x05, 0xd1, 0x2e, 0xe5, 0x84, 0x4f, 0x47, 0x49, 0x6a, 0x71, 0x89, 0x3e, 0x92,
	0xf9, 0xfa, 0xc5, 0xa5, 0x49, 0x05, 0xd9, 0xe9, 0x60, 0x0a, 0xe1, 0x04, 0xa5, 0xf9, 0x8c, 0x5c,
	0x6c, 0xfe, 0x49, 0x59, 0xa9, 0xc9, 0x25, 0x42, 0x29, 0x5c, 0xdc, 0xce, 0xa5, 0xc5, 0x25, 0xf9,
	0xb9, 0x6e, 0x99, 0xa9, 0x39, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x4e, 0x4e, 0xb7, 0xee,
	0xc9, 0xdb, 0x91, 0x61, 0x8f, 0x1e, 0xc4, 0xa8, 0x90, 0xca, 0x82, 0xd4, 0x20, 0x64, 0x63, 0x85,
	0xf4, 0xb9, 0x38, 0x83, 0x4b, 0x93, 0x20, 0x56, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0x09,
	0xea, 0x41, 0xf5, 0xc0, 0x25, 0x82, 0x10, 0x6a, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x2a,
	0x9c, 0x47, 0x32, 0x01, 0x00, 0x00,
}
